// Helper: regenerates lib/src/specs/v1/wcag_2_2_embedded.dart from the source YAML.
// Run it manually whenever you edit the base spec.
//
//   dart run tool/embed_spec.dart
import 'dart:io';

void main() {
  final yaml = File('lib/src/specs/v1.0.0/wcag_2_2.yaml').readAsStringSync();
  if (yaml.contains("'''")) {
    stderr.writeln('YAML contains triple single-quote, cannot embed safely.');
    exit(1);
  }
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/embed_spec.dart. Do not edit by hand.')
    ..writeln('// Source: lib/src/specs/v1.0.0/wcag_2_2.yaml')
    ..writeln('')
    ..writeln("const String wcag22V1Yaml = r'''")
    ..write(yaml)
    ..writeln("''';");
  File('lib/src/specs/v1.0.0/wcag_2_2_embedded.dart')
      .writeAsStringSync(out.toString());
  print('Embedded ${yaml.length} chars into wcag_2_2_embedded.dart');
}