import 'widget_discovery.dart';

/// Generates the content of an `ethos.yaml` file from a [DiscoveryResult].
///
/// The output is a valid YAML file with:
/// - A header explaining what to do next.
/// - A `widget_aliases` block for each discovered custom widget,
///   with all optional fields commented out so the developer fills them in.
/// - A `color_aliases` block for each unresolvable color expression,
///   fully commented out since hex values require human knowledge.
class EthosYamlGenerator {
  /// Generates the full `ethos.yaml` content from [result].
  ///
  /// [projectPath] is used only for the header comment.
  static String generate(DiscoveryResult result, {String? projectPath}) {
    final buffer = StringBuffer();

    _writeHeader(buffer, result, projectPath: projectPath);

    if (result.widgetUsages.isNotEmpty) {
      _writeWidgetAliases(buffer, result.widgetUsages);
    }

    if (result.colorExpressions.isNotEmpty) {
      _writeColorAliases(buffer, result.colorExpressions);
    }

    _writeRuleOverridesExample(buffer);

    return buffer.toString();
  }

  static void _writeHeader(
    StringBuffer buffer,
    DiscoveryResult result, {
    String? projectPath,
  }) {
    buffer.writeln('# ethos.yaml — generated by `ethos init`');
    if (projectPath != null) {
      buffer.writeln('# Project: $projectPath');
    }
    buffer.writeln('#');
    buffer.writeln('# Ethos found:');
    buffer.writeln('#   ${result.totalWidgets} custom widget(s) used 3+ times');
    buffer
        .writeln('#   ${result.totalColors} color expression(s) used 3+ times');
    buffer.writeln('#');
    buffer.writeln('# What to do:');
    buffer
        .writeln('#   1. For each widget_alias: set role, uncomment label_arg');
    buffer.writeln('#      and size/keyboard fields if applicable.');
    buffer.writeln('#   2. For each color_alias: uncomment and fill in');
    buffer.writeln('#      foreground and background hex values.');
    buffer.writeln('#   3. Run `ethos -p . -v` to see the effect.');
    buffer.writeln('#');
    buffer.writeln('# Docs: https://github.com/gearscrafter/ethos');
    buffer.writeln('');
  }

  static void _writeWidgetAliases(
    StringBuffer buffer,
    Map<String, int> widgetUsages,
  ) {
    buffer.writeln('widget_aliases:');
    buffer.writeln('');

    for (final entry in widgetUsages.entries) {
      final name = entry.key;
      final count = entry.value;

      buffer.writeln('  # $name — used $count time${count == 1 ? "" : "s"}');
      buffer.writeln('  $name:');
      buffer.writeln('    role: button         '
          '# button | text | input — REQUIRED');
      buffer.writeln('    # label_arg: ???     '
          '# e.g. semanticLabel, a11yLabel, label');
      buffer.writeln('    # size_guaranteed: true   '
          '# uncomment if already >= 48x48 internally');
      buffer.writeln('    # keyboard_ready: true    '
          '# uncomment if keyboard-operable out of the box');
      buffer.writeln('');
    }
  }

  static void _writeColorAliases(
    StringBuffer buffer,
    Map<String, int> colorExpressions,
  ) {
    buffer.writeln('color_aliases:');
    buffer.writeln(
        '  # Uncomment each entry and fill in your actual hex values.');
    buffer.writeln('  # foreground: required. background: optional but needed');
    buffer.writeln('  # for contrast ratio calculation.');
    buffer.writeln('');

    for (final entry in colorExpressions.entries) {
      final expr = entry.key;
      final count = entry.value;

      final yamlKey = _needsQuotes(expr) ? '"$expr"' : expr;

      buffer.writeln('  # used $count time${count == 1 ? "" : "s"}');
      buffer.writeln('  # $yamlKey:');
      buffer.writeln('  #   foreground: "#REPLACE_ME"   # text color');
      buffer.writeln('  #   background: "#REPLACE_ME"   # background color');
      buffer.writeln('');
    }
  }

  static void _writeRuleOverridesExample(StringBuffer buffer) {
    buffer.writeln('# Optional: override per-rule thresholds.');
    buffer.writeln('# rule_overrides:');
    buffer.writeln('#   wcag_1_4_3_contrast_minimum:');
    buffer.writeln('#     critical_threshold: 95');
  }

  static bool _needsQuotes(String key) {
    const specials = [
      '\$',
      ':',
      '#',
      '{',
      '}',
      '[',
      ']',
      ',',
      '&',
      '*',
      '?',
      '|',
      '-',
      '<',
      '>',
      '=',
      '!',
      '%',
      '@',
      '`'
    ];
    return specials.any((c) => key.contains(c));
  }
}
